kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: repd-west1-b-c
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-standard
  replication-type: regional-pd
  zones: us-west1-b, us-west1-c